apiVersion: v1
kind: Service
metadata:
  name: {{ include "fabricx.fullname" . }}-auth
  labels:
    {{- include "fabricx.labels" (dict "root" . "name" "auth-service") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "fabricx.labels" (dict "root" . "name" "auth-service") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.authService.service.port }}
      targetPort: http
